image: asia.gcr.io/inbox-gcr/devops/builder:mvn-sbt-node

variables:
  KONG_DOMAIN: k8s.insuranceinbox.com
  DOCKER_REGISTRY: asia.gcr.io/inbox-gcr/projects
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

.bootstrap: &bootstrap
  before_script:
    - echo "🔐 Logging in to GCR..."
    - docker login -u _json_key -p "$INBOX_GCR_ACCESS_KEY" https://asia.gcr.io
  after_script:
    - docker system prune -af --volumes

build:
  <<: *bootstrap
  image: asia.gcr.io/inbox-gcr/devops/builder:mvn-sbt-node
  tags:
    - docker
  stage: build
  script:
    - echo "Building Docker image for pipeline ${CI_PIPELINE_ID}"
    - docker builder prune -af || true
    - docker build --no-cache -t "${DOCKER_REGISTRY}/data-ingestion:${CI_PIPELINE_ID}" -f Dockerfile .
    - docker push "${DOCKER_REGISTRY}/data-ingestion:${CI_PIPELINE_ID}"
  rules:
    - if: $CI_COMMIT_BRANCH == "backup-jun10"
