apiVersion: v1
kind: Service
metadata:
  name: data-ingestion
  labels:
    app.kubernetes.io/name: data-ingestion
    app.kubernetes.io/part-of: upsure
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: data-ingestion
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
